apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cvye
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0032-tenant/ci1t-43256-0032-app/devfile-sample-cvye@sha256:16ed770ced07ddabcf1193366d9111c1c1661f7225cb639ca624397a3e6b90a3
        name: my-nodejs
        resources: {}
status: {}
