apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cvye
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cvye
    app.kubernetes.io/part-of: ci1t-43256-0032-app
  name: devfile-sample-cvye
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cvye
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cvye
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0032-tenant/ci1t-43256-0032-app/devfile-sample-cvye@sha256:16ed770ced07ddabcf1193366d9111c1c1661f7225cb639ca624397a3e6b90a3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
